### ISSUE TITLE
[Feature request] Press [E] to access the Clothing Shop

### ISSUE THREAD

**Issue by NexDK** [esx-framework/esx_clotheshop#14]
**Make it soo that the notification "Press [E] to access the Clothing Shop" goes away when you open the shop and comes back when closing the menu like esx_barbershop**

![Skærmbillede 2023-09-26 032048](https://github.com/esx-framework/esx_clotheshop/assets/36231983/f6d799f3-39d5-4e27-b201-7c4c49dffd5d)

**Comment by Arctos2win** [comment]
hey @NexDK, 

i updated the repo, now the textui will open and close 
on menu close and open.

**Comment by NexDK** [comment]
Amazing :-)
