### ISSUE TITLE
[bug] confirm purchase menu

### ISSUE THREAD

**Issue by NexDK** [esx-framework/esx_clotheshop#16]
**The confirm purchase menu does not close when you "confirm - yes" your purchase**

![Skærmbillede 2023-09-29 130918](https://github.com/esx-framework/esx_clotheshop/assets/36231983/b6f9e602-8329-424f-88dc-b7da3d297f8d)

**Comment by Arctos2win** [comment]
@NexDK open a support post, bcs i don't have this problem.

**Comment by NexDK** [comment]
i found a fix for now, by adding "ESX.CloseContext()" to the bought function

```
if bought then
    TriggerEvent('skinchanger:getSkin', function(skin)
    TriggerServerEvent('esx_skin:save', skin)
    ESX.CloseContext()
end)
```

**Comment by TheBGamer** [comment]
The problem persists. Cannot manage to get past this:
![image_2023-12-29_200012702](https://github.com/esx-framework/esx_clotheshop/assets/87948499/ae076024-e109-4750-86f2-507cd1fbf753)
